
/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of Advocate
 *
 * @constructor
 */
Advocate = function (obj) {
    if(!obj) {
        this.name = null;     
        this.lastname = null;     
        this.email = null;     
        this.payoutThreshold = null;     
        this.avatarUrl = null;     
        this.metadata = null;     
        this.canRefer  = true;     
        //Append to variable dictionary
        this._variableDict['payoutThreshold'] = 'payout_threshold';
        this._variableDict['avatarUrl'] = 'avatar_url';
        this._variableDict['canRefer'] = 'can_refer';
    } else {
        this.name = (obj.name !== undefined && obj.name !== null)? obj.name : null;
        this.lastname = (obj.lastname !== undefined && obj.lastname !== null)? obj.lastname : null;
        this.email = (obj.email !== undefined && obj.email !== null)? obj.email : null;
        this.payoutThreshold = (obj.payout_threshold !== undefined && obj.payout_threshold !== null)? obj.payout_threshold : null;
        this.avatarUrl = (obj.avatar_url !== undefined && obj.avatar_url !== null)? obj.avatar_url : null;
        this.metadata = (obj.metadata !== undefined && obj.metadata !== null)? obj.metadata : null;
        this.canRefer = (obj.can_refer !== undefined && obj.can_refer !== null)? obj.can_refer : null;
        //Append to variable dictionary
        this._variableDict['payoutThreshold'] = 'payout_threshold';
        this._variableDict['avatarUrl'] = 'avatar_url';
        this._variableDict['canRefer'] = 'can_refer';
    }
};

Advocate.prototype = new BaseModel();
Advocate.prototype.constructor = Advocate;

/**
 * The advocate's name
 *
 * @return {string}
 */
Advocate.prototype.getName = function() {
    return this.name;
};

/**
 * Setter for Name
 * 
 * @param {string} value 
 */
Advocate.prototype.setName = function(value) {
    this.name = value;
};

/**
 * The advocate's last name
 *
 * @return {string}
 */
Advocate.prototype.getLastname = function() {
    return this.lastname;
};

/**
 * Setter for Lastname
 * 
 * @param {string} value 
 */
Advocate.prototype.setLastname = function(value) {
    this.lastname = value;
};

/**
 * The advocate's email
 *
 * @return {string}
 */
Advocate.prototype.getEmail = function() {
    return this.email;
};

/**
 * Setter for Email
 * 
 * @param {string} value 
 */
Advocate.prototype.setEmail = function(value) {
    this.email = value;
};

/**
 * The total amount of bonuses that the advocate must generate before being able to create a bonus redemption request.
 *
 * @return {int}
 */
Advocate.prototype.getPayoutThreshold = function() {
    return this.payoutThreshold;
};

/**
 * Setter for PayoutThreshold
 * 
 * @param {int} value 
 */
Advocate.prototype.setPayoutThreshold = function(value) {
    this.payoutThreshold = value;
};

/**
 * The advocate's avatar URL
 *
 * @return {string|null}
 */
Advocate.prototype.getAvatarUrl = function() {
    return this.avatarUrl;
};

/**
 * Setter for AvatarUrl
 * 
 * @param {string|null} value 
 */
Advocate.prototype.setAvatarUrl = function(value) {
    this.avatarUrl = value;
};

/**
 * Useful to store extra information about the advocate. e.g, the phone number, address, etc.
 *
 * @return {string|null}
 */
Advocate.prototype.getMetadata = function() {
    return this.metadata;
};

/**
 * Setter for Metadata
 * 
 * @param {string|null} value 
 */
Advocate.prototype.setMetadata = function(value) {
    this.metadata = value;
};

/**
 * Whether or not the advocate is allowed to refer services/products (Useful when using the Full Widget template).
 *
 * @return {bool|null}
 */
Advocate.prototype.getCanRefer = function() {
    return this.canRefer;
};

/**
 * Setter for CanRefer
 * 
 * @param {bool|null} value 
 */
Advocate.prototype.setCanRefer = function(value) {
    this.canRefer = value;
};


module.exports = Advocate;
