
/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of AdvocateForm
 *
 * @constructor
 */
AdvocateForm = function (obj) {
    if(!obj) {
        this.advocate = null;     
    } else {
        this.advocate = (obj.advocate !== undefined && obj.advocate !== null)? new Advocate(obj.advocate) : null;
    }
};

AdvocateForm.prototype = new BaseModel();
AdvocateForm.prototype.constructor = AdvocateForm;

/**
 * The advocate's wrapper
 *
 * @return {Advocate}
 */
AdvocateForm.prototype.getAdvocate = function() {
    return this.advocate;
};

/**
 * Setter for Advocate
 * 
 * @param {Advocate} value 
 */
AdvocateForm.prototype.setAdvocate = function(value) {
    this.advocate = value;
};


module.exports = AdvocateForm;
