
/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of BonusesForm
 *
 * @constructor
 */
BonusesForm = function (obj) {
    if(!obj) {
        this.bonus = null;     
    } else {
        this.bonus = (obj.bonus !== undefined && obj.bonus !== null)? new Bonuses(obj.bonus) : null;
    }
};

BonusesForm.prototype = new BaseModel();
BonusesForm.prototype.constructor = BonusesForm;

/**
 * The bonuses' wrapper
 *
 * @return {Bonuses}
 */
BonusesForm.prototype.getBonus = function() {
    return this.bonus;
};

/**
 * Setter for Bonus
 * 
 * @param {Bonuses} value 
 */
BonusesForm.prototype.setBonus = function(value) {
    this.bonus = value;
};


module.exports = BonusesForm;
