
/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of ForceBonusesForm
 *
 * @constructor
 */
ForceBonusesForm = function (obj) {
    if(!obj) {
        this.bonus = null;     
    } else {
        this.bonus = (obj.bonus !== undefined && obj.bonus !== null)? new ForceBonuses(obj.bonus) : null;
    }
};

ForceBonusesForm.prototype = new BaseModel();
ForceBonusesForm.prototype.constructor = ForceBonusesForm;

/**
 * The bonuses' wrapper
 *
 * @return {ForceBonuses}
 */
ForceBonusesForm.prototype.getBonus = function() {
    return this.bonus;
};

/**
 * Setter for Bonus
 * 
 * @param {ForceBonuses} value 
 */
ForceBonusesForm.prototype.setBonus = function(value) {
    this.bonus = value;
};


module.exports = ForceBonusesForm;
