
/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of Referral
 *
 * @constructor
 */
Referral = function (obj) {
    if(!obj) {
        this.referredAdvocateToken = null;     
        this.referralOriginSlug = null;     
        this.campaignSlug = null;     
        this.httpReferer = null;     
        //Append to variable dictionary
        this._variableDict['referredAdvocateToken'] = 'referred_advocate_token';
        this._variableDict['referralOriginSlug'] = 'referral_origin_slug';
        this._variableDict['campaignSlug'] = 'campaign_slug';
        this._variableDict['httpReferer'] = 'http_referer';
    } else {
        this.referredAdvocateToken = (obj.referred_advocate_token !== undefined && obj.referred_advocate_token !== null)? obj.referred_advocate_token : null;
        this.referralOriginSlug = (obj.referral_origin_slug !== undefined && obj.referral_origin_slug !== null)? obj.referral_origin_slug : null;
        this.campaignSlug = (obj.campaign_slug !== undefined && obj.campaign_slug !== null)? obj.campaign_slug : null;
        this.httpReferer = (obj.http_referer !== undefined && obj.http_referer !== null)? obj.http_referer : null;
        //Append to variable dictionary
        this._variableDict['referredAdvocateToken'] = 'referred_advocate_token';
        this._variableDict['referralOriginSlug'] = 'referral_origin_slug';
        this._variableDict['campaignSlug'] = 'campaign_slug';
        this._variableDict['httpReferer'] = 'http_referer';
    }
};

Referral.prototype = new BaseModel();
Referral.prototype.constructor = Referral;

/**
 * The referrals token
 *
 * @return {string}
 */
Referral.prototype.getReferredAdvocateToken = function() {
    return this.referredAdvocateToken;
};

/**
 * Setter for ReferredAdvocateToken
 * 
 * @param {string} value 
 */
Referral.prototype.setReferredAdvocateToken = function(value) {
    this.referredAdvocateToken = value;
};

/**
 * The referral origin identifier
 *
 * @return {string}
 */
Referral.prototype.getReferralOriginSlug = function() {
    return this.referralOriginSlug;
};

/**
 * Setter for ReferralOriginSlug
 * 
 * @param {string} value 
 */
Referral.prototype.setReferralOriginSlug = function(value) {
    this.referralOriginSlug = value;
};

/**
 * The campaign identifier
 *
 * @return {string}
 */
Referral.prototype.getCampaignSlug = function() {
    return this.campaignSlug;
};

/**
 * Setter for CampaignSlug
 * 
 * @param {string} value 
 */
Referral.prototype.setCampaignSlug = function(value) {
    this.campaignSlug = value;
};

/**
 * The http_referrer URL
 *
 * @return {string}
 */
Referral.prototype.getHttpReferer = function() {
    return this.httpReferer;
};

/**
 * Setter for HttpReferer
 * 
 * @param {string} value 
 */
Referral.prototype.setHttpReferer = function(value) {
    this.httpReferer = value;
};


module.exports = Referral;
