
/**
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var BaseModel = require("./BaseModel");

/**
 * Creates an instance of ReferralForm
 *
 * @constructor
 */
ReferralForm = function (obj) {
    if(!obj) {
        this.referral = null;     
    } else {
        this.referral = (obj.referral !== undefined && obj.referral !== null)? new Referral(obj.referral) : null;
    }
};

ReferralForm.prototype = new BaseModel();
ReferralForm.prototype.constructor = ReferralForm;

/**
 * The referral's wrapper
 *
 * @return {Referral}
 */
ReferralForm.prototype.getReferral = function() {
    return this.referral;
};

/**
 * Setter for Referral
 * 
 * @param {Referral} value 
 */
ReferralForm.prototype.setReferral = function(value) {
    this.referral = value;
};


module.exports = ReferralForm;
